apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins-plugin-demo-project
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    # jenkins-jobUrl: http://localhost:8080/job/SimplePipeline
    # jenkins.io/job-full-name: SimplePipeline
    jenkins-jobUrl: http://localhost:8080/job/My-GitHub-Pipeline
    jenkins.io/job-full-name: My-GitHub-Pipeline
spec:
  type: service
  owner: gowtham@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins-plugin-demo-project
  description: test pipeline-2
  annotations:
    jenkins-jobUrl: http://localhost:8080/job/SimplePipeline
    jenkins.io/job-full-name: SimplePipeline
spec:
  type: service
  owner: gowthamd@example.com
  lifecycle: production
